# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PigeonholeCli < Formula
  desc "Sending your secrets securely!"
  homepage "https://pigeono.io"
  version "0.4.23"

  on_macos do
    on_intel do
      url "https://releases.pigeono.io/0.4.23/darwin/amd64/pigeonhole.tar.gz"
      sha256 "285986cb9b45370c6fcef454e8ed37aaf59db33b1075304d27388682e976843c"

      def install
        bin.install "0.4.23/darwin/amd64/pigeonhole"
      end
    end
    on_arm do
      url "https://releases.pigeono.io/0.4.23/darwin/arm64/pigeonhole.tar.gz"
      sha256 "0ae9976641118480c828ecb81a0e22fb21678487d9b6f4b2888f89e7ad7d1681"

      def install
        bin.install "0.4.23/darwin/arm64/pigeonhole"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.pigeono.io/0.4.23/linux/amd64/pigeonhole.tar.gz"
        sha256 "c02d9ac7de0648b51bda8585cb1b3e8e0293257eb791a9e18e661b7cf2028518"

        def install
          bin.install "0.4.23/linux/amd64/pigeonhole"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.pigeono.io/0.4.23/linux/arm64/pigeonhole.tar.gz"
        sha256 "c575c7d092c069b77ec82e80a81c3898019db1cc0f693be892304576abfa54ff"

        def install
          bin.install "0.4.23/linux/arm64/pigeonhole"
        end
      end
    end
  end
end
