# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PigeonholeCli < Formula
  desc "Sending your secrets securely!"
  homepage "https://pigeono.io"
  version "0.4.19"

  on_macos do
    on_intel do
      url "https://releases.pigeono.io/0.4.19/darwin/amd64/pigeonhole.tar.gz"
      sha256 "a434d01d18745b93947e6186d5e2c94d6193b5a3dfe6da7c2501e83b189589d7"

      def install
        bin.install "0.4.19/darwin/amd64/pigeonhole"
      end
    end
    on_arm do
      url "https://releases.pigeono.io/0.4.19/darwin/arm64/pigeonhole.tar.gz"
      sha256 "e27ffcf9325d38c88cc3c49a3fbc84cc28b206f44fc27a44e6db9b4e04ebe1da"

      def install
        bin.install "0.4.19/darwin/arm64/pigeonhole"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.pigeono.io/0.4.19/linux/amd64/pigeonhole.tar.gz"
        sha256 "763711459b3e87ac9d886e586faa537b86ea461c6e945c015a387d3dd3363190"

        def install
          bin.install "0.4.19/linux/amd64/pigeonhole"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.pigeono.io/0.4.19/linux/arm64/pigeonhole.tar.gz"
        sha256 "4f1a986212ea2bd1d3f483a4e4002a53f0fd162e4139ebb2c83390ea1903ebcd"

        def install
          bin.install "0.4.19/linux/arm64/pigeonhole"
        end
      end
    end
  end
end
