# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PigeonholeCli < Formula
  desc ""
  homepage "https://pigeono.io"
  version "0.4.11"

  on_macos do
    on_intel do
      url "https://releases.pigeono.io/0.4.11/darwin/amd64/pigeonhole"
      sha256 "d85409aaf466eeb738ff3b45a2c8b106c3c1c06fbd5be39a84eeabaf94ad033d"

      def install
        bin.install "pigeonhole-cli/0.4.11/darwin/amd64/pigeonhole"
      end
    end
    on_arm do
      url "https://releases.pigeono.io/0.4.11/darwin/arm64/pigeonhole"
      sha256 "ca339e25541afdd7a74f633375bcdceb80e555cae70e883fff8e0e240f3efcc0"

      def install
        bin.install "pigeonhole-cli/0.4.11/darwin/arm64/pigeonhole"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.pigeono.io/0.4.11/linux/amd64/pigeonhole"
        sha256 "86880902b14c7a4dce098c67911e077644cde210ef173d992760a7fc45d2cf3c"

        def install
          bin.install "pigeonhole-cli/0.4.11/linux/amd64/pigeonhole"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.pigeono.io/0.4.11/linux/arm64/pigeonhole"
        sha256 "6ace0d758c5b238158906ed178412d6c124331d0a3c77fba00ecb6f530c138c1"

        def install
          bin.install "pigeonhole-cli/0.4.11/linux/arm64/pigeonhole"
        end
      end
    end
  end
end
