# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PigeonholeCli < Formula
  desc ""
  homepage ""
  version "1.2.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.9/pigeonhole-cli_1.2.9_darwin_amd64.tar.gz"
      sha256 "d4b45fdbf09aed5a34008b61c1cdb96e41dc37cf307f49513671a7210b2b8ade"

      def install
        bin.install "pigeonhole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.9/pigeonhole-cli_1.2.9_darwin_arm64.tar.gz"
      sha256 "67b7298915b0f4ca99e9f23f1ed244abf508bb043abcde59c174ee4ce1c60776"

      def install
        bin.install "pigeonhole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.9/pigeonhole-cli_1.2.9_linux_amd64.tar.gz"
      sha256 "6ff8f4c16a8cc7d25ed922f685d7ad042fe28b942291db0733eb5776a1a00ef6"
      def install
        bin.install "pigeonhole"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.9/pigeonhole-cli_1.2.9_linux_arm64.tar.gz"
      sha256 "4123b9095b6d65ea467ef3f5f678c0afca36754b962abe845c673e9b546fa53b"
      def install
        bin.install "pigeonhole"
      end
    end
  end
end
