# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PigeonholeCli < Formula
  desc ""
  homepage ""
  version "1.2.66"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.66/pigeonhole-cli_1.2.66_darwin_amd64.tar.gz"
      sha256 "4db6246fe2553238d5736936cab7e7ebd7e0a28a9b8f630e5238525173dfc244"

      def install
        bin.install "pigeonhole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.66/pigeonhole-cli_1.2.66_darwin_arm64.tar.gz"
      sha256 "156b77bd3839b98cbaf6b8fbf43055926ea8a04f447ba0f19548c3c13a4d7275"

      def install
        bin.install "pigeonhole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.66/pigeonhole-cli_1.2.66_linux_amd64.tar.gz"
      sha256 "bfd04b535422e2bcd48fdeb0f00528a7541f53a9187e768b80030bc4318fbe42"
      def install
        bin.install "pigeonhole"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pigeonholeio/pigeonhole-cli/releases/download/1.2.66/pigeonhole-cli_1.2.66_linux_arm64.tar.gz"
      sha256 "7f013d29b449e89bf58f9a2003fe281c6b4033c0a7f7490daf3fb1144a39f951"
      def install
        bin.install "pigeonhole"
      end
    end
  end
end
